(fix) upgrade python packages to avoid pip installation problems     * pyOpenSSL versions earlier than 17.0 cause a known error to pip: "AttributeError: 'module' object has no attribute 'SSL_ST_INIT'"     * earlier cryptography version fail to build, also incompatible with recent pyOpenSSL     * merge common packages for prod/dev